### ISSUE TITLE
Customizing UI

### ISSUE THREAD

**Issue by 1N50MN14** [Mhusain/FacebookAccountKit#1]
First thank you for putting the plugin up! 

It would've been great if there was a way to customize the UI colors, both iOS and Android expose a Theme class, we could potentially pass a JSON object to the plugin constructor with the different color values which in turn could internally be applied to the UI theme ;)

**Comment by Mhusain** [comment]
Appreciating your feedback.

I'll work on this as I get some time.

**Comment by Mhusain** [comment]
Added functionality to customize the UI colors, both iOS and Android.
