### ISSUE TITLE
Email login / android response not returned 

### ISSUE THREAD

**Issue by 1N50MN14** [Mhusain/FacebookAccountKit#3]
When signing in with email on Android I'm encountering two issues:

1. The "Open App" app link does not open the app (whereas this works on iOS)

2. Since I've been already authenticated, AccountKit displays a successful login message when manually opening the app again, but the plugin does not trigger a success response

**Comment by Mhusain** [comment]
I have checked this and "Open App" not working but manually working is fine.

your second issue not generated at my end.
