### ISSUE TITLE
ios un defined FcaebookAccountKit variable

### ISSUE THREAD

**Issue by MoustafaBayommy** [Mhusain/FacebookAccountKit#4]
when using the plugin android it work just fine ,but with iOS it give me  the type of FacebookAccountKit is undefined any hints , or this is an issue ??

**Comment by Mhusain** [comment]
I have just created a sample project for you to test the issue but it was not generated. Please make sure you have latest Cordova version or try to reinstall the plugin.

Cordova version is 6.4.0 and cordova-ios version is 4.3.1

**Comment by MoustafaBayommy** [comment]
my ionic info
Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 7.3.1 Build version 7D1014

how do I install Cordova-ios or use it ,sorry   new in Cordova world

**Comment by Mhusain** [comment]
Just simply create a new project via following below steps through your terminal in mac:

1.  cordova create hello com.example.hello HelloWorld
2. cd hello
3. cordova platform add ios --save
4. cordova plugin add cordova-plugin-facebook-account-kit --save --variable APP_ID="XXXXXX" --variable APP_NAME="hello" --variable AK_TOKEN="XXXXXXX"

and then use ::

FacebookAccountKit.emailLogin(function (response) { alert(JSON.stringify(response)); }, function (error) { console.log(error) });

**Comment by MoustafaBayommy** [comment]
I create blank project and take your steps it works fine. but when I try to work in my current project by removing platform then re add it and re add the plugin it work once then after trying to emulate again it doesn't work , it seem like it isn't the plugin issue .thanks for your time

**Comment by MoustafaBayommy** [comment]
I figure out what is my problem ,I was  add the facebookAccuntKit code out side device.ready 
...but how it worked by this mistake in android I don't know after replace the code in right place it works . thanks for your help

**Comment by MoustafaBayommy** [comment]
their is one only question left if you help me with it you are my life saver ...how can I customize the look of Facebook account kit  them...my regarded

**Comment by Mhusain** [comment]
I am very glad for you that its worked.

I believe that you can customise the look of Facebook account kit in settings of your app created @
https://developers.facebook.com/apps

I will also add the functionality to customise the look from plugin also in upcoming days.

**Comment by MoustafaBayommy** [comment]
I try to go throw official one like that 


loginViewController.delegate = self;

  AKTheme *theme = [AKTheme themeWithPrimaryColor:[UIColor redColor]
                                 primaryTextColor:[UIColor whiteColor]
                                   secondaryColor:[UIColor colorWithRed:1.0 green:0.8 blue:0.8 alpha:1.0]
                               secondaryTextColor:[UIColor darkGrayColor]
                                   statusBarStyle:UIStatusBarStyleLightContent];
  loginViewController.theme = [Themes theme];



and I add it but it give me error such ::AKTheme  not fount replace by AKFTThem 

and also Theme un defined

**Comment by Mhusain** [comment]
There is a GUI available for this.
https://developers.facebook.com/docs/accountkit/customizingemail

**Comment by MoustafaBayommy** [comment]
thanks a lot  but this tool for web use  not iOS .
thanks a lot for you precious time

**Comment by Mhusain** [comment]
Added functionality to customize the UI colors, both iOS and Android. Please download the latest version.
