### ISSUE TITLE
integrate with ionic 2

### ISSUE THREAD

**Issue by mrpower55** [Mhusain/FacebookAccountKit#5]
it is really looking nice and i want to ask if this is compatiable with ionic 2
i tried to download it but i don't know how to import it in my typescript file

so please if anyone know how please tell me
thanks

**Comment by rajbisht13** [comment]
Hey we can use this plugin in ionic2 app?

**Comment by amitanmol** [comment]
Yes, we can use in Ionic also. We can use same command line for Ionic.
For example:

$cordova plugin add cordova-plugin-facebook-account-kit --save --variable APP_ID="123456789" --variable APP_NAME="myApplication" --variable AK_TOKEN="AccountKitClientToken"
